url = "https://vra8.lab.domain.local/"
project_name = "vRA 8 Project Name Here"
blueprint_id = "Blueprint GUID HERE"
blueprint_version = "Blueprint Version Here"
deployment_name = "CentOS Terraform Deployment"
